### ISSUE TITLE
Issue while connecting to pingdom on google app server.

### ISSUE THREAD

**Issue by braindevoiler** [KennethWilke/PingdomLib#31]
I am trying to use PingdomLib to connect a django application on Google App Engine, but I am getting the following exception related to SSL. I couldn't find anything on google to solve this. Please look into this.

INFO 2016-05-12 11:31:32,447 connectionpool.py:788] Starting new HTTPS connection (1): api.pingdom.com
Internal Server Error: /
Traceback (most recent call last):
File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/django-1.5/django/core/handlers/base.py", line 113, in get_response
response = callback(request, _callback_args, *_callback_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/Application/views.py", line 6, in index
pingdomchecks = api.getChecks()
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/pingdomlib/pingdom.py", line 212, in getChecks
response = self.request('GET', 'checks', parameters)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/pingdomlib/pingdom.py", line 66, in request
headers=headers)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/api.py", line 71, in get
return request('get', url, params=params, *_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/api.py", line 57, in request
return session.request(method=method, url=url, *_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/sessions.py", line 475, in request
resp = self.send(prep, *_send_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/sessions.py", line 585, in send
r = adapter.send(request, *_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/adapters.py", line 477, in send
raise SSLError(e, request=request)
SSLError: Can't connect to HTTPS URL because the SSL module is not available.
ERROR2016-05-12 11:31:32,447 base.py:210] Internal Server Error: /
Traceback (most recent call last):
File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/django-1.5/django/core/handlers/base.py", line 113, in get_response  
response = callback(request, _callback_args, *_callback_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/Application/views.py", line 6, in index
pingdomchecks = api.getChecks()
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/pingdomlib/pingdom.py", line 212, in getChecks
response = self.request('GET', 'checks', parameters)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/pingdomlib/pingdom.py", line 66, in request
headers=headers)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/api.py", line 71, in get
return request('get', url, params=params, *_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/api.py", line 57, in request
return session.request(method=method, url=url, *_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/sessions.py", line 475, in request
resp = self.send(prep, *_send_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/sessions.py", line 585, in send
r = adapter.send(request, *_kwargs)
File "/Users/ankur/Documents/Ankur/ApplicationMonitor/lib/requests/adapters.py", line 477, in send
raise SSLError(e, request=request)
SSLError: Can't connect to HTTPS URL because the SSL module is not available.
INFO 2016-05-12 11:31:32,524 module.py:788] default: "GET / HTTP/1.1" 500 83729

**Comment by KennethWilke** [comment]
Hi @ankurgupta123, looks like the error message you have there states "Can't connect to HTTPS URL because the SSL module is not available." I've not tested this library on a system without ssl support, but it looks like you might need to install a python module for that.

**Comment by ankurgupta123** [comment]
Hi @KennethWilke, It's working fine on django application, but there are some issues when used on Google App Engine. I am able to run same on AWS EB.

**Comment by KennethWilke** [comment]
I don't have any familiarity with Google's App Engine, but I found this doc that has some information on getting SSL to work on it:

https://cloud.google.com/appengine/docs/python/sockets/ssl_support
